package com.utap.tidy.data

import com.google.firebase.Timestamp
import com.google.firebase.firestore.ServerTimestamp

data class CleanJob(
        var jobTitle: String? = null,
        var responsiblePerson: String? = null,
        var lastUpdateTime: Timestamp? = null,
        @ServerTimestamp
        val timeStamp: Timestamp? = null,
        var score: Int? = null,
        var frequency: Int? = null,
        // rowID is generated by firestore, used as primary key
        var rowID: String = ""
)